### ISSUE TITLE
Kan vi lage en iOS app av denne?

### ISSUE THREAD

**Issue by robinnydahl** [skulstadv/OOProject#3]

**Comment by skulstadv** [comment]
Vi kan det ja. Spørsmålet er; vil vi?

**Comment by robinnydahl** [comment]
Er jo en ganske så stor brukergruppe... Mulig @RuneBergh har noen innvendiger på dette(?).

**Comment by RuneBergh** [comment]
helt klart!! det bruker vi all tid på fremover, og en Dapp

**Comment by robinnydahl** [comment]
Veldig bra. Da setter jeg issuen som løst og setter opp en feature request.
